name: Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.repository == 'ChristopherMayes/LUME-Impact' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: lume-impact-dev
          environment-file: environment.yml

      #- name: Execute notebooks
      #  shell: bash -l {0}
      #  run: |
      #    pip install --no-dependencies . 
      #    scripts/execute_notebooks.bash 

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          zip -r lume-impact-examples.zip docs/examples/
          mv lume-impact-examples.zip ./site/assets/.
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
