name: Publish Documentation

on:
  push:
    branches:
      - master
  release:
    types:
      - published

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and deploy docs"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/conda-setup
        with:
          python-version: ${{ matrix.python-version }}
          extras: "doc"
      #- name: Execute notebooks
      #  shell: bash -l {0}
      #  run: |
      #    pip install --no-dependencies . 
      #    scripts/execute_notebooks.bash 
      - name: Build Docs
        shell: bash -l {0}
        run: mkdocs build
      - name: Extract examples
        shell: bash -l {0}
        run: |
          zip -r lume-impact-examples.zip docs/examples/
          mv lume-impact-examples.zip ./site/assets/
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site
  deploy:
    if: ${{ github.repository == 'ChristopherMayes/lume-impact' }}
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
