name: Run tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        
    name: Test Suite
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
      - name: Create environment
        shell: bash -l {0}
        run: |
          mamba config --set always_yes yes --set changeps1 no
          mamba install --yes --file requirements.txt
          mamba install --yes --file dev-requirements.txt
          mamba install impact-t
          pip install --no-dependencies .
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -vv
