name: Run tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
    name: Test model execution
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: flexible
      - name: Create environment
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install --yes --file requirements.txt
          conda install --yes --file dev-requirements.txt
          pip install -e .
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
